#!/recovery/bin/sh

mount -t proc proc /proc

echo "Starting mdevd..."
mount -t tmpfs mdev /dev
mount -t sysfs sysfs /sys
echo /recovery/sbin/mdev > /proc/sys/kernel/hotplug

mount -t ramfs    ramfs    /tmp
mkdir /dev/pts
#mkdir /dev/shm
mount -t  devpts  devpts   /dev/pts
#mount -t  tmpfs   tmpfs    /dev/shm
mount -t  debugfs none     /sys/kernel/debug

mount -o remount,rw /
mount -t jffs2  mtd:imagefs /mnt/imagefs
mount -t jffs2  mtd:resource /mnt/resource
#mount -t jffs2 mtd:userdata /mnt/userdata

mdev -s

fs_check_recovery "recovery"
# ZTE_MBB modify
mtdnum_zterw=$(cat /proc/mtd | grep "zterw" | awk '{print $1}'| cut -b 4- |sed 's/://g')
ubiattach /dev/ubi_ctrl  -d 2 -m $mtdnum_zterw
mount -t ubifs -o rw ubi2_0 /zfota
echo system_lock > /sys/power/wake_lock
# ZTE_MBB end
mkdir -p /mnt/userdata/cache /mnt/userdata/etc_rw /mnt/userdata/var

echo "Starting FOTA Recovery application!"

# start fota upi
#fota_upi --upgrade system &
prestartdua recovery &
